# Generated by Django 4.2.6 on 2024-10-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
